language: go

go:
    - 1.6

script:
    - ./scripts/test.sh
    - ./build.sh

after_script:
    - ./autobd -h

notifications:
    email:
        recipients:
            - tyrell.wkeene@gmail.com
        on_success: change
        on_failure: always
