language: go

go:
    - 1.4.2

install:
    -

before_script:
    - go get github.com/constabulary/gb/...
    - cd $GOPATH/src/github.com/constabulary/gb
    - go install -v -a ./...
    - cd $TRAVIS_BUILD_DIR

script:
    - ./build.sh

notifications:
    email:
        recipients:
            - tyrell.wkeene@gmail.com
        on_success: change
        on_failure: always
