language: go

go:
    - 1.5
    - 1.6
    - 1.7.5

script:
    - ./build.sh

after_script:
    - ./autobd -h

notifications:
    email:
        recipients:
            - tyrell.wkeene@gmail.com
        on_success: change
        on_failure: always
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/5a76f0d5acf7e446e7af
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
