language: go

go:
    - 1.4.2

before_script:
    - cd src/github.com/SaviorPhoenix/autobd

script:
    - ./build.sh

notifications:
    email:
        recipients:
            - tyrell.wkeene@gmail.com
        on_success: change
        on_failure: always
