#Which directory to serve
root_dir = "test/client"

#The port the API will listen on
api_port = "8080"

#Run as a node
run_as_node = true

[node]
#What server to communicate with IP/URL
#(required when running as a node)
seed_servers = ["http://0.0.0.0:8081"]

#How often to update with the other servers
update_interval = "1m"
