#Which directory to serve
root_dir = "/home/autobd-node/data"

#The port the API will listen on
api_port = "8080"

#Path to the TLS certificate to use when running as server
tls_cert = "./secret/cert.pem"

#Path to the key associated with the TLS certificate used by the server
tls_key = "./secret/key.pem"

#Run as a node
run_as_node = true

[node]
#What server to communicate with IP/URL
#(required when running as a node)
seed_servers = ["http://172.18.0.2:8080", "http://172.18.0.3:8080", "http://172.18.0.4:8080"]

#How often to update with the other servers
update_interval = "1m"
